apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: ovh-credentials
  namespace: cert-manager
spec:
  organizationId: 22e5f56f-b852-41c6-ab00-b34601341f88 
  secretName: ovh-credentials                
  onlyMappedSecrets: true
  authToken:
    secretName: bw-auth-token                
    secretKey: token
  map:
  - bwSecretId: 804e4a4d-ee18-479e-88ed-b3bb00c2372f
    secretKeyName: applicationConsumerKey
  - bwSecretId: e055f14b-6e79-4997-ab4a-b3bb00c25305
    secretKeyName: applicationKey
  - bwSecretId: f9b77275-5157-484d-81d1-b3bb00c264d1
    secretKeyName: applicationSecret
