apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: cert-manager
type: Opaque
data:
  applicationConsumerKey: MGQ5NmFlNTkzMzUyZDZmZmY4NDNiMjJkMjFiOTBjNDM=
  applicationKey: NDA0YTZmMWY4MDcyZTIxYg==
  applicationSecret: NTRlODE4MWFkOTJjNTU3NDQwYjEyNDQ0NTU0ZjA5YTQ=
