---
- name: Create K3S Worker
  become: true
  block:
    - name: Determining interface to setup
      ansible.builtin.set_fact:
        vlan_number: "{{ proxmox_tags | regex_search('k3s-egress-gateway-vlan-(\\d+)', '\\1') | first | default('') }}"

    - name: "Enable DHCP with custom settings on ens18.{{ vlan_number }}"
      ansible.builtin.blockinfile:
        path: "/run/systemd/network/10-netplan-ens18.{{ vlan_number }}.network"
        block: |
          DHCP=ipv4
          [DHCP]
          RouteMetric=100
          UseMTU=true
        backup: true

    - name: Restart systemd-networkd and request lease
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted