---
- name: Create K3S Worker
  block:
  - name: Get K3S token from master
    ansible.builtin.slurp:
      src: /var/lib/rancher/k3s/server/node-token
    delegate_to: "{{ k3s_master_host }}"
    run_once: true
    register: k3s_token_file

  - name: "Ensure .kube directory exists for {{ node_username }}"
    file:
      path: "/home/{{ node_username }}/.kube"
      state: directory
      owner: "{{ node_username }}"
      group: "{{ node_username }}"
      mode: 0700

  - name: Download and install k3s agent
    shell: |
      curl -sfL {{ k3s_url }} | K3S_URL=https://{{ k3s_master_ip }}:6443 K3S_TOKEN={{ k3s_token_file.content | b64decode | trim }} sh -
    args:
      creates: /usr/local/bin/k3s
      
  - name: Ensure Cilium Hubble port 4244/tcp is open
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 4244
      jump: ACCEPT
      comment: "Cilium Hubble gRPC"

  - name: "Labelling {{ inventory_hostname }} for VLAN 50"
    kubernetes.core.k8s:
      state: present
      name: "{{ inventory_hostname }}"
      definition:
        apiVersion: v1
        kind: Node
        metadata:
          labels:
            affected_vlan: "50"
      kubeconfig: "{{ local_kubeconfig_path }}"
    delegate_to: localhost
    when: "'k3s-worker-node-50' in proxmox_tags.split(';')"

  - name: "Labelling {{ inventory_hostname }} for VLAN 60"
    kubernetes.core.k8s:
      state: present
      name: "{{ inventory_hostname }}"
      definition:
        apiVersion: v1
        kind: Node
        metadata:
          labels:
            affected_vlan: "60"
      kubeconfig: "{{ local_kubeconfig_path }}"
    delegate_to: localhost
    when: "'k3s-worker-node-60' in proxmox_tags.split(';')"

  become: true
