---
- name: Create K3S Egress gateway
  become: true
  block:
    - name: Determining interface to setup
      ansible.builtin.set_fact:
        vlan_number: "{{ proxmox_tags | regex_search('k3s-egress-gateway-vlan-(\\d+)', '\\1') | first | default('') }}"

    - name: "Enable DHCP with custom settings on ens18.{{ vlan_number }}"
      ansible.builtin.blockinfile:
        path: "/run/systemd/network/10-netplan-ens18.{{ vlan_number }}.network"
        block: |
          DHCP=ipv4
          [DHCP]
          UseRoutes=false
          UseDNS=false
          UseGateway=false
          RouteMetric=2048
          UseMTU=true
        backup: true

    - name: Restart systemd-networkd and request lease
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted

    - name: "Labelling {{ inventory_hostname }} for egress gateway {{ vlan_number }}"
      kubernetes.core.k8s:
        state: present
        name: "{{ inventory_hostname }}"
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            labels:
              egress: "{{ vlan_number }}"
        kubeconfig: "{{ local_kubeconfig_path }}"
      delegate_to: localhost

    - name: Ensure Cilium egress gateway policy exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cilium.io/v2
          kind: CiliumEgressGatewayPolicy
          metadata:
            name: "egress-vlan{{ vlan_number }}"
          spec:
            egressGateway:
              nodeSelector:
                matchLabels:
                  egress: "{{ vlan_number }}"
              interface: "ens18.{{ vlan_number }}"
            destinationCIDRs:
              - 0.0.0.0/0
            selectors:
              - namespaceSelector:
                  matchLabels:
                    use-egress: "{{ vlan_number }}"
        kubeconfig: "{{ local_kubeconfig_path }}"
      delegate_to: localhost
      run_once: true
      when: vlan_number != ""
